### ISSUE TITLE
Don't mix units in contract.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/second-price-auction#12]
The contract is using indivisible tokens as units for some variables in the contracts and this makes it _really_ hard to audit.  The contract should use indivisible units _everywhere_ and _only_ deal with divisible units (e.g., 1 ETH or 1 DOT) at the UI layer.  Everywhere else it should deal with `attoeth` and `millidot`.

I'm currently trying to figure out if the conversions are done correctly everywhere but it is proving incredibly difficult due to the mixed units.

**Comment by MicahZoltu** [comment]
I believe there is in fact a bug around this in `calculateEndTime` where you are dividing `tokenCap` (which is a number of dot not millidot) by `DIVISOR` (1000).  If the token sale is for 5000 DOT then this means the factor will be 5 * 10^18 / 250.  I don't _believe_ this is right, but it is hard to tell intent in this context.

**Comment by gavofyork** [comment]
It doesn't mix units, at least not with `tokenCap` - that's milliDOTs.

**Comment by MicahZoltu** [comment]
@gavofyork Is this comment incorrect then?  https://github.com/paritytech/second-price-auction/blob/master/src/contracts/SecondPriceAuction.sol#L47

> Token cap should take be in whole tokens, not smallest divisible units.
