### ISSUE TITLE
Remove `inject`.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/second-price-auction#14]
I'm not sure what the intent of `inject` is, but it makes this ICO heavily trusted rather than untrusted since the admin can give away however many tokens they want to whomever they want.  On top of this, anyone added to the ICO via inject gets a bonus even if it is outside the bonus period or after the sale is over.

With functions like this included in the contract, it does not really make sense to run an on-chain auction at all and you would be much better suited to just running a centralized trusted auction instead.  If the admin can effectively "do whatever they want" then there really isn't any point in using a blockchain to manage the auction.  Just let people send you ETH and then you promise to give them some undefined number of DOTs at some point in the future (either as an Ethereum token or as Polkadot DOTs).

**Comment by keorn** [comment]
Only bounded number of tokens will ever exist, see FrozenToken.

**Comment by MicahZoltu** [comment]
The contracts, currently, are designed such that the second price auction contract can be used with any token.  This means that the auction contract should not be relying on implementation details of `FrozenToken` for providing trust guarantees.  If this auction is designed to only work with a specific implementation of a token, I recommend combining them into a single file and changing the type from a generic `Token` to `FrozenToken` to make it clear to the reader that this _only_ works with `FrozenToken`.

Also, even though the total number of tokens given away may be capped by the token supply of `FrozenToken`, the admin can, after all tokens have been distributed but before all tokens have been finalized create a bunch of faux sales using `inject` and then finalise them which would result in people who had previously sent ETH to the contract not getting any tokens in return because the sale is over-subscribed.  The issue here is that `inject` has _no_ constraints on it such as "there are any tokens left to sell" or "the sale is over".

**Comment by MicahZoltu** [comment]
In fact, it gets worse.  If `inject` is called after the tokens are sold out, the `totalAccounted` will increase likely causing the contract to never fire the Retire event because `totalAccounted` will never equal `totalFinalized` (the transfer will start failing before that happens). ~and anyone who had finalized prior to `inject` being called would get a better deal on the tokens than people who called `finalize` after `inject` was called.~

**Comment by MicahZoltu** [comment]
This function can also be used to reset the `endTime` via overflow as well as do some pathological things to the various state variables with overflows.

There are so many attacks possible via this function that I would simply assert that the admin has the ability to set any state variable to whatever they want.  While this isn't technically true, I think it should be assumed to be true as long as this function exists in its current form as the admin can _really_ screw with state via this function.

**Comment by keorn** [comment]
`before_beginning` modifier should suffice

**Comment by gavofyork** [comment]
I generally disagree with the sentiment of "this contract depends on `FrozenToken`". Guarantees can be delivered in parts.

**Comment by MicahZoltu** [comment]
If I get a chance I'll re-review with `before_beginning` as that addresses most of my original issues.
