### ISSUE TITLE
Don't use opaque formulas without reasoning behind them.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/second-price-auction#15]
https://github.com/paritytech/second-price-auction/blob/master/src/contracts/SecondPriceAuction.sol#L178
https://github.com/paritytech/second-price-auction/blob/master/src/contracts/SecondPriceAuction.sol#L186

These two formulas have a couple of un-named constants that make them incredibly opaque as to what their intent is.  Also, the provenance of the formula is not mentioned anywhere which makes it hard to analyze whether they are achieving the desired goal (because the desired goal is not described anywhere).

Recommend changing unnamed constants to named constants or local variables.
Recommend including clear documentation on what the formula is doing, where it comes from, and what it is attempting to achieve.

At a higher level I recommend a strategy that doesn't depend on opaque formula and instead takes a more naive/simpler approach to improve auditability.  While the formula may be correct, it makes it notably harder to audit the system than a more naive/simple implementation of the goals.

**Comment by keorn** [comment]
There is not logarithms in which would make it easier. Will add comment with justification.

**Comment by gavofyork** [comment]
Well, the graph is really just a bunch of anonymous constants - it's not like they ever had names. It doesn't really come from anywhere - it was custom designed. What it is attempting to achieve and its general description is out of scope for this codebase, but should certainly be done should this contract be used in the wild.
