### ISSUE TITLE
Remove unused interface methods.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/second-price-auction#19]
https://github.com/paritytech/second-price-auction/blob/master/src/contracts/MultiCertifier.sol#L23-L25

These three functions are no-op functions and aren't ever called.  Including them causes confusion for readers/auditors and may result in a bug being introduced down the road by someone calling them without them being implemented.

Recommend removing them or implementing/using them.

**Comment by gavofyork** [comment]
It's a wholesale import from the `Certifier` contract. Implementation would be sensible (in a pedantic sort of way :) ) though, yeah.
