### ISSUE TITLE
Fix the `Era` concept.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/second-price-auction#20]
https://github.com/paritytech/second-price-auction/blob/master/src/contracts/SecondPriceAuction.sol#L43-L44 suggests that `Ticked` will be called every ~20 blocks, but in reality it will be called every 5 minutes.  If you mean minutes, say minutes.  If you mean blocks, say blocks.  At the moment block time is in the mid 20s so 5 minutes != 20 blocks.

https://github.com/paritytech/second-price-auction/blob/master/src/contracts/SecondPriceAuction.sol#L156-L163 is called and updates the `eraIndex` state variable but that state variable is never used outside of this function.  This suggests that the function is used _solely_ to log an event every 5 minutes indicating current status.  This is somewhat pointless as you can construct current status via the other events that are fired via an off-chain process.  It does add a _minor_ convenience as one can scan for that log specifically to get periodic updates, but you won't be able to use any generic tooling since the contract is going to spit out a _ton_ of other events that will make it incredibly hard to find that event without custom tooling.  If you have custom tooling, you might as well just write the custom tooling to track all of the events and build state in-memory.

Alternatively, simply consider adding the two variables of interest to the `BuyIn` event.  It will cost all users a bit more gas, but at least the gas costs will then be more predictable rather than having unpredictable gas costs.  Since you are logging anyway, the additional gas cost of a couple non-indexed items on the event is fairly marginal compared to other parts of the system.

**Comment by gavofyork** [comment]
Eras are used to facilitate graphing Dapps which cannot reasonably be expected to process and track ~10,000 events to instead get rough tracking data. I agree it's not ideal and would better be done off-chain, but the code is simple and isolated from the main logic & state and it's not a huge gas cost, and, practically-speaking, makes the difference between having a graphing dapp and not having a graphing dapp.

The comment is sorted in e4f6fc75d08462378acb7401b293294acc8d19fd .
