### ISSUE TITLE
Delete certificate rather than just clearing `active`.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/second-price-auction#22]
https://github.com/paritytech/second-price-auction/blob/master/src/contracts/MultiCertifier.sol#L60 only clears the `active` flag but doesn't clear the certifier or the entry.  There does not appear to be any purpose to leaving an inactive certificate as it isn't used anywhere.

Recommend either make use of revoked certificates, add a comment indicating why revoked certificates are useful and why the log isn't enough, or `delete certs[_who]` .  If you go with the last, consider also removing the `.active` storage variable and the struct and simplifying to a `mapping(address => address)` to save on gas.

**Comment by gavofyork** [comment]
Leaving it there, in principle, allows one to distinguish between certified-and-then-revoked (or some other attempt at certification that was for some reason unsuccessful) and not certified at all.
