### ISSUE TITLE
Don't call local methods with `this.`

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/second-price-auction#8]
https://github.com/paritytech/second-price-auction/blob/master/src/contracts/SecondPriceAuction.sol#L211

The call to `this.bonus(_value)` will result in an internal transaction (e.g., `.call`) rather than a local jump instruction.  This costs significantly more gas and also changes `msg.sender` which can result in unexpected behavior.

Recommend changing the line to:
```
uint _bonus = bonus(_value);
```
Note: You will need a different variable name for the local `bonus` variable.  Further recommend following a pattern that results in different naming convention for local variables vs storage variables/functions (e.g., `_` prefix on all local variables).

**Comment by gavofyork** [comment]
fixed.
