### ISSUE TITLE
Design Security: Do not constrain users to non-contracts or freeze tokens for extended periods of time.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/second-price-auction#9]
https://github.com/ethereum/EIPs/pull/208/ will largely remove the difference between accounts and contracts.

Also, limiting the auction to only EOAs means that no one can participate using any kind of enhanced security like multi-sig wallets, recoverable wallets, etc.  This creates a problem where the contract is indirectly reducing the ability of participants to secure their assets.  Since it appears the intention is to make the token non-transferable (`FrozenToken`), this means that a participant cannot effectively secure their assets against loss/theft using modern techniques such as multi-sig wallets or recoverable wallets.

Having a long-term illiquid assets is also a security concern as users that are using an EOA, such as a hardware wallet, cannot transfer their assets to a secure account should their EOA become potentially compromised.  An example situation is if a user is using a hardware wallet with their recovery phrase in cold storage.  Should the hardware wallet fail before the tokens are unfrozen and the recovery phrase has to be pulled out of cold storage, the user now is put into a situation where they are using a wallet to store their DOTs without being able to effectively secure them.

### Argumentation

The reasons for having the tokens remain illiquid are unclear from past conversations with the Polkadot team.  I have yet to hear a compelling argument from _any_ token sale that has sold illiquid tokens (and I have spoken with _many_).  When ICOs take actions without strong reasoning, it is either because they are malicious in some way or they think they are clever.  I have seen _many_ token sales occur where the designers thought they were clever but they didn't share their cleverness with auditors/public until after the fact and once they did it turned out they were in fact not nearly as clever as they thought they were. 
 If they would have solicited external feedback on their cleverness they would have been shown why they aren't in fact very clever.

I consider token sales that introducing security risks without a _strong_ argument as why they are necessary to be a giant red flag.  I recommend people avoid tokens with red flags and find other places to spend their money.

Either provide a compelling argument for why the tokens should be illiquid despite the end-user security vulnerabilities it introduces, or allow people to effectively secure their assets by making the token liquid.  At the least, the token should support contracts so people can take measures to secure their assets despite the attack vectors introduced by having an illiquid token.

**Comment by gavofyork** [comment]
There are no hard plans to make these tokens an Ethereum-based asset. Allowing them to be "owned" by an arbitrary Ethereum account would necessitate that.

This is in line with the Ethereum sale which for not entirely dissimilar reasons required people to "own" their "asset" through a secret key during the network development period.
